FROM maven:3.6.3-jdk-8
ADD https://jdbc.postgresql.org/download/postgresql-42.3.3.jar /opt
ADD https://dist.apache.org/repos/dist/release/ranger/2.2.0/apache-ranger-2.2.0.tar.gz /opt

COPY scripts/ranger-entrypoint.sh /opt

WORKDIR /opt

RUN apt-get -q update && apt-get install -y -q python3 gcc \
 && mkdir apache-ranger-2.2.0 \
 && tar zxf apache-ranger-2.2.0.tar.gz -C apache-ranger-2.2.0

RUN cd apache-ranger-2.2.0 \
 && mvn -Pall -DskipTests=true clean compile package install assembly:assembly

RUN cp target/ranger-2.2.0-admin.tar.gz /opt \
 && cd /opt \
 && tar zxf ranger-2.2.0-admin.tar.gz \
 && chmod +x /opt/ranger-entrypoint.sh

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
ENV RANGER_HOME=/opt/ranger-2.2.0-admin

RUN ln -s $RANGER_HOME ranger-admin

COPY utils/install.properties ${RANGER_HOME}

EXPOSE 6080
ENTRYPOINT ["/opt/ranger-entrypoint.sh"]